### ISSUE TITLE
Float timecodes get converted to integer timecodes

### ISSUE THREAD

**Issue by tuxa** [nu774/mp4fpsmod#25]
When I use the tool to transfer floating-point timecodes to an mp4 the resulting timecodes get converted to integers. 

Input:
```
# timecode format v2
0
156.688888888889
190.011111111111
223.333333333333
256.655555555556
289.977777777778
323.3
```

Output:
```
# timecode format v2
0
157
190
224
257
290
324
```

This should be the code piece that does the cast:

`DTS(i) = CTS(i) = static_cast<uint64_t>(timeCodes[i] + 0.5);`

Is it possible to add support for floating-point timecodes, or is there a reason DTS and CTS are integers?

**Comment by nu774** [comment]
MP4(ISOBMFF) file uses integer to describe time but allows arbitrary timescale (also in integer) which is the time unit per second.  For example, if timescale is 1000, time value of 40 means 40/1000 second (that is, 40 millisecond).

When importing from timecode_v2 file, mp4fpsmod will try to pick up some appropriate timescale if given timecode exactly matches some common NTSC/PAL fps (30000/1000 and the like). Otherwise, mp4fpsmod will use 1000 as the default timescale. 

When exporting to timecode_v2 file, mp4fpsmod can write floating point timecodes. However, if timescale is 1000, every timestamp in the file can be described in integer milliseconds.
That's why you get integer numbers.

**Comment by tuxa** [comment]
Thanks for the detailed answer! So, setting the timescale to a higher value gives floating point times. I just tested it and it works like charm :+1:
